### INDEX
GET http://localhost:3000/songs

### READ/SHOW
GET http://localhost:3000/songs/2

### CREATE
POST http://localhost:3000/songs
content-type: application/json

{
  "title": "Bananaphone",
  "album": "Kids Songs",
  "artist": "Raffi",
  "year": 2004
}

### UPDATE
PATCH http://localhost:3000/songs/4
content-type: application/json

{
  "title": "new title",
  "album": "untitled album"
}

### DELETE/DESTROY
DELETE http://localhost:3000/songs/4